Make `markdownlint-cli2` more discoverable
igorshubovych/markdownlint-cli pull request #329
Opened 2022-10-12 12:42 UTC by AlekSi

2022-10-12 16:12 UTC, DavidAnson requested changes
Good idea!

2022-10-12 16:12 UTC, DavidAnson commented on README.md
> +- [markdownlint-cli2][markdownlint-cli2] - another CLI
Thanks! Could you please capitalize'A' for consistency?

2022-10-12 16:12 UTC, DavidAnson commented on README.md
> +[markdownlint-cli2]: https://github.com/DavidAnson/markdownlint-cli2
This list is not fully sorted, but could you move this line below "markdownlint", please?

2022-10-19 03:31 UTC, DavidAnson approved these changes

2022-10-19 03:31 UTC, merged

2022-10-19 03:39 UTC, AlekSi commented
Oops, sorry, missed your comments. Thank you!